name: Release (Tag-Based)
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ext: deb
          - os: windows-latest
            ext: exe
          - os: macos-latest
            ext: pkg
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get OS info
        run: mvn enforcer:display-info
        
      - name: List active profiles
        run: mvn help:active-profiles "-Dpackager.javapackager"

      - name: Build
        run: mvn clean package "-Dpackager.javapackager"
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: AmerecoLauncher_${{ runner.os }}-${{ runner.arch }}.${{ matrix.ext }}
          path: target/AmerecoLauncher*.${{ matrix.ext }}
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AmerecoLauncher*/AmerecoLauncher*
          tag_name: ${{ github.ref_name }}
#          body: "Automated release of ${{ github.ref_name }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}